plugin: aws_ec2

  #aws_access_key: AKIA3UTK7BBH4T323GGH
  #aws_secret_key: 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
regions:
  - ap-south-1

filters:
  instance-state-name : running

keyed_groups:
  - key: tags.Name
    prefix: ""
    seperator: ""

hostnames:
  - private-ip-address

compose:
    ansible_host: private_ip_address
